FROM quay.io/keycloak/keycloak:22.0.1 AS builder
# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres
ENV KC_HOSTNAME_STRICT=false
ENV KC_PROXY_HEADERS=forwarded
ENV KC_HTTP_ENABLED=true
ENV KC_HTTP_PORT=8080
# V2201
ENV KC_PROXY_MODE=edge
ENV KC_DB_URL_PROPERTIES="?allowPublicKeyRetrieval=true&useSSL=false"
ENV KC_FEATURES='declarative-user-profile'

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore

RUN /opt/keycloak/bin/kc.sh build


FROM quay.io/keycloak/keycloak:22.0.1
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# Copy realm import file
COPY realm-export.json /opt/keycloak/data/import/realm-export.json

# change these values to point to a running postgres instance
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_DB=postgres
ENV KC_HOSTNAME_STRICT=false
ENV KC_PROXY_HEADERS=forwarded
ENV KC_HTTP_ENABLED=true
ENV KC_HTTP_PORT=8080
# V2201
ENV KC_PROXY_MODE=edge
ENV KC_DB_URL_PROPERTIES="?allowPublicKeyRetrieval=true&useSSL=false"
ENV KC_FEATURES='declarative-user-profile'

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "--verbose" ,"start", "--optimized", "--import-realm"]